"use strict";
var name = "Mike";
var model = "Asus Rog Strix G";
var deskno = 23;
console.log(`Name: ${name}`);
console.log(`Laptop Model: ${model}`);
console.log(`DeskNo: ${deskno}`);
document.write(`Name: ${name}`);
document.write(`Laptop Model: ${model}`);
document.write(`DeskNo: ${deskno}`);
